[project]
name = "prod-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
    "langsmith>=0.14.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "slowapi>=0.1.10",
    "uvicorn>=0.54.0",
]

[project.scripts]
prod-rag = "prod_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
